spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/paf_db
spring.datasource.username=root
spring.datasource.password=root # Change this to your actual MySQL password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true